### ISSUE TITLE
Add water/flood depth algorithm(s)

### ISSUE THREAD

**Issue by ArjenHaag** [Servir-Mekong/hydra-floods#12]
Should add the water/flood depth algorithm(s), e.g. FwDET-GEE and the (improved?) version I've been working on myself.

**Comment by KMarkert** [comment]
This would be great to have! Can we create a new module for terrain related functionality. Maybe something like `topo.py`?

**Comment by KMarkert** [comment]
This was fully implemented with e7c19aca64515d5bd23cccb1ff4318bfc59cdfe0
