### ISSUE TITLE
Lookups for default parameters

### ISSUE THREAD

**Issue by ArjenHaag** [Servir-Mekong/hydra-floods#13]
When setting default function parameters per sensor there could be two options.

Option 1: create a `defaults.py` module and add keywords as dictionaries. This way users can quickly import that module and get the suggested function parameters per sensor. Something like:
```python
s1 = {
    'edge_otsu': {
        'initial_threshold':-16,
        'edge_buffer': 300,
         ...
    },
    ...
}

'landsat' = {'edge_otsu':{...},...}
```
Pro would be that users can access the defaults easily and pass directly to the functions whether using the datasets classes, image collections, or simply images (i.e. `water = hf.edge_otsu(s1_img, **defaults.s1['edge_otsu'])`). Con would it can be that the sensor lookup variable names may be different than what a user is expecting/knows.

Option 2: include these defaults within the sensor dataset classes as object parameters, see [`datasets.py`](https://github.com/Servir-Mekong/hydra-floods/blob/empty-hist/hydrafloods/datasets.py). Pro would be if a user is working directly with the dataset objects they can call the defaults directly from there (i.e. `water = s1.apply_func(hf.edge_otsu, **s1.edge_otsu_defaults)`). Con would be users would have to use the dataset classes to get the defaults.

Let me know your thoughts. Again I feel like this would be very helpful, especially to new users that may not know what parameters to use.

_Originally posted by @KMarkert in https://github.com/Servir-Mekong/hydra-floods/issues/11#issuecomment-732480827_

**Comment by KMarkert** [comment]
@ArjenHaag Thinking on this a bit more, we can probably do a hybrid of options one and two. 

If we create a file (defaults.py) that has the defaults in it as dictionary info as suggested in option1 we can import that into datasets.py and parse the correct defaults for the different datasets. This way from a user's standpoint it is actually in two places but we only need to maintain one copy in defaults.py

Thoughts? If this sounds like a good idea, I can work on it.

**Comment by ArjenHaag** [comment]
Great idea. Probably doesn't even have to be a .py file, could also be .ini or something else slightly more user friendly / readable? Although doesn't matter much. Go for it :)
