### ISSUE TITLE
Errors when using DSWFP

### ISSUE THREAD

**Issue by lg760411** [Servir-Mekong/hydra-floods#21]
Hi, I just learn to use Hydrafloods in python. When try the code of DSWFP, Step 1 is OK. But When I run Step 2 with the module export_surface_water_harmonics and Step 3 export_daily_surface_water, It failed for errors"'str' object has no attribute 'limit'", I can not know what happened. Here are the code:
region = ee.Geometry.Rectangle([114, 24.3, 115, 25.1 ])#龙南
start_time = "2015-01-01"
end_time = "2020-01-01"
input_features = ["VV","VH","ratio","ndpi"] # SAR features to predict water index
target_label = "mndwi" # water index to predict
fusion_fc = output_asset # the ouput asset name from the earlier block
ouput_asset = "users/liuguangxu/surface_water_harmonic_coefficients"

dswfp.export_surface_water_harmonics(
    region, 
    start_time, 
    end_time, 
    #feature_names= input_features, 
    #label= target_label, 
    fusion_samples=fusion_fc, 
    output_asset_path=None, 
    #tile=False
)
The result is :
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-33b72beb6c36> in <module>
     11 ouput_asset = "users/liuguangxu/surface_water_harmonic_coefficients"
     12 
---> 13 dswfp.export_surface_water_harmonics(
     14     region,
     15     start_time,

C:\ProgramData\Anaconda3\lib\site-packages\hydrafloods\workflows\dswfp.py in export_surface_water_harmonics(region, start_time, end_time, output_asset_path, n_cycles, feature_names, label, fusion_samples, tile, tile_size, output_scale)
    302             fusion_model, scaling_dict = ml.random_forest_ee(
    303                 25,
--> 304                 fusion_samples.limit(10000),
    305                 feature_names,
    306                 label,

AttributeError: 'str' object has no attribute 'limit'
Thanks.

**Comment by KMarkert** [comment]
Hi @lg760411 👋 
You are getting this error because internally in the `dswfp` module the process is limiting the number of samples so that it efficiently build a random forest model without too much training data. Seems like you are passing a string for the `fusion_fc` variable.
This issue can be fixed by making `fusion_fc` a feature collection: `fusion_fc = ee.FeatureCollection(output_asset)`

**Comment by lg760411** [comment]
@KMarkert 
Thank you for your help. The second step is OK now. 
But Step3 rasied another problem when export_daily_surface_water : 'export_daily_surface_water() got an unexpected keyword argument 'harmonic_coefs'
I add 'ee.Image(= "users/liuguangxu/surface_water_harmonic_coefficients")' but it can not work.
I close it, as well as 'harmonic_collection=None', '#output_confidence=True'. Yet it stile failed. How can I set the parameters for them？ Below is the code:
target_date = "2020-05-07"

dswfp.export_daily_surface_water(
    region, 
    target_date, 
    #harmonic_coefs= None, 
    #harmonic_collection=None, 
    feature_names=None, 
    label=None, 
    look_back=30, 
    #output_confidence=True, 
    fusion_samples=ee.FeatureCollection("users/liuguangxu/fusion_sampling_20190101_20190701"), 
    output_asset_path=None,
    initial_threshold=0.1,
    thresh_no_data=-0.1,
    tile=False
)

and The errors:
EEException                               Traceback (most recent call last)
<ipython-input-480-4608db5e489a> in <module>
      1 target_date = "2020-05-07"
      2 
----> 3 dswfp.export_daily_surface_water(
      4     region,
      5     target_date,

C:\ProgramData\Anaconda3\lib\site-packages\hydrafloods\workflows\dswfp.py in export_daily_surface_water(region, target_date, harmonic_image, harmonic_collection, feature_names, label, look_back, lag, n_cycles, include_confidence, include_flood, export_fusion, fusion_samples, output_asset_path, output_bucket_path, initial_threshold, thresh_no_data, tile, tile_size, tile_buffer, output_scale)
    546 
    547         if fusion_samples is not None:
--> 548             fusion_model, scaling_dict = ml.random_forest_ee(
    549                 25,
    550                 fusion_samples.limit(10000),

C:\ProgramData\Anaconda3\lib\site-packages\hydrafloods\ml.py in random_forest_ee(n_trees, feature_collection, feature_names, label, scaling, mode)
    291 
    292     elif scaling == "standard":
--> 293         scaling_dict = standard_scaling_dict(feature_collection, feature_names)
    294         fc_norm = standard_feature_scaling(
    295             feature_collection, scaling_dict, feature_names

C:\ProgramData\Anaconda3\lib\site-packages\hydrafloods\ml.py in standard_scaling_dict(fc, feature_names)
    100     # force ee types
    101     fc = ee.FeatureCollection(fc)
--> 102     ee_feature_names = ee.List(feature_names)
    103 
    104     # get a combined reducer for caluclating mean and standard dev

C:\ProgramData\Anaconda3\lib\site-packages\ee\computedobject.py in __call__(cls, *args, **kwargs)
     30       return args[0]
     31     else:
---> 32       return type.__call__(cls, *args, **kwargs)
     33 
     34 

C:\ProgramData\Anaconda3\lib\site-packages\ee\ee_list.py in __init__(self, arg)
     39       self._list = None
     40     else:
---> 41       raise ee_exception.EEException(
     42           'Invalid argument specified for ee.List(): %s' % arg)
     43 

EEException: Invalid argument specified for ee.List(): None

**Comment by KMarkert** [comment]
As you guessed, there are a couple keyword arguments missing or the inputs are not the expected type. Specifically, you are missing the following:
 * `harmonic_coefs` - ee.Image output from step 2, 
 * `feature_names` - same list as step 2, 
 * `label` - same string as step 2, and 
 * `output_asset_path` - this is the asset path to write surface water map to

Please change the function execution to the following:

```
dswfp.export_daily_surface_water(
    region,
    target_date,
    harmonic_coefs= "users/liuguangxu/surface_water_harmonic_coefficients",
    feature_names=["VV","VH","ratio","ndpi"],
    label="mndwi",
    look_back=30,
    fusion_samples=ee.FeatureCollection("users/liuguangxu/fusion_sampling_20190101_20190701"),
    output_asset_path="users/liuguangxu/test_dswfp_out",
    initial_threshold=0.1,
    thresh_no_data=-0.1,
    tile=False
)
```

Please let me know if those changes works.

**Comment by lg760411** [comment]
Hi, Kel,
Thanks for  your message. I changed and run it again. It shows here:
target_date = "2019-05-07"
dswfp.export_daily_surface_water(
    region,
    target_date,
    harmonic_image= ee.Image("users/liuguangxu/surface_water_harmonic_coefficients"),
    feature_names=["VV","VH","ratio","ndpi"],
    label="mndwi",
    look_back=30,
    fusion_samples=ee.FeatureCollection("users/liuguangxu/fusion_sampling_20190101_20190701"),
    output_asset_path="users/liuguangxu/test_dswfp_out",
    initial_threshold=0.1,
    thresh_no_data=-0.1,
    tile=False
)
Errors: 
ValueError                                Traceback (most recent call last)
<ipython-input-485-5bf4f74e1b16> in <module>      1 target_date ="2019-05-07"----> 2 dswfp.export_daily_surface_water(
      3     region,      4     target_date,      5     harmonic_image= ee.Image("users/liuguangxu/surface_water_harmonic_coefficients"),C:\ProgramData\Anaconda3\lib\site-packages\hydrafloods\workflows\dswfp.py in export_daily_surface_water(region, target_date, harmonic_image, harmonic_collection, feature_names, label, look_back, lag, n_cycles, include_confidence, include_flood, export_fusion, fusion_samples, output_asset_path, output_bucket_path, initial_threshold, thresh_no_data, tile, tile_size, tile_buffer, output_scale)    560    561         now = datetime.datetime.now()--> 562time_id = now.strftime("%Y%m%d%H%M%s")    563         time_str = now.strftime("%Y-%m-%d %H:%M:%s")    564ValueError: Invalid format string
On 4/3/2021 02:04，Kel ***@***.***> wrote：

As you guessed, there are a couple keyword arguments missing or the inputs are not the expected type. Specifically, you are missing the following:

harmonic_coefs - ee.Image output from step 2,
feature_names - same list as step 2,
label - same string as step 2, and
output_asset_path - this is the asset path to write surface water map to

Please change the function execution to the following:

dswfp.export_daily_surface_water(
    region,
    target_date,
    harmonic_coefs= "users/liuguangxu/surface_water_harmonic_coefficients",
    feature_names=["VV","VH","ratio","ndpi"],
    label="mndwi",
    look_back=30,
    fusion_samples=ee.FeatureCollection("users/liuguangxu/fusion_sampling_20190101_20190701"),
    output_asset_path="users/liuguangxu/test_dswfp_out",
    initial_threshold=0.1,
    thresh_no_data=-0.1,
    tile=False
)


Please let me know if those changes works.

**Comment by KMarkert** [comment]
Hmmm...this looks like there was an error when formatting the datetime object as a string. Can you please provide only the error message that Python output so that it will be easier to pinpoint where exactly the error originated from?
