### ISSUE TITLE
Attribute Error for add_fusion_features

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#30]
First of all, I am running the code in Google Colaboratory  on Python 3.7.12. 

In the final code block of the "Getting Started" section, "under the "Machine Learning" subheader, the first line of code in the very last code block is as follows 

#add bands for features used in RF model 
s1_features = s1.add_fusion_features() 

when I attempt to run this code, I get the following error message 

"Attribute Error: 'Sentinel1' object has no attribute 'add_fusion_features'

P.S. This is the only error I have encountered in the Hydrafloods documentation so far. Thank you so much for providing such a helpful and easy-to-follow introduction to this tool!

**Comment by KMarkert** [comment]
Thanks for reporting this error. The method `.add_fusion_features()` no longer exists and has been replaced with a combination of different methods. I will update the documentation to reflect these changes in the API.

**Comment by KMarkert** [comment]
This was fixed with commit d1a0bdd4e04293b1ad2aa7457de9975523a22af6
