### ISSUE TITLE
example code from main page not working for me

### ISSUE THREAD

**Issue by RussellGrew** [Servir-Mekong/hydra-floods#31]
Hi,

I am very excited to try this out. Thanks for making it available.

I run the example from `readme.md`  as-is and the output in Earth Engine isn't happy about the dates. See screenshot.

![image](https://user-images.githubusercontent.com/42530666/147166685-374fc320-1153-4222-9e09-27bc81845c41.png)

Advice invited.

Thanks!

**Comment by KMarkert** [comment]
Hi @RussellGrew ,
Thanks for reporting this. The result you shared is actually what is expected, the line `water_map = ee.Image(water_imgs.collection.mode())` applies a reducer on the collection to mosaic the multiple scenes together. In doing so the date information (and other metadata) is dropped. To add the date information back in for the result you can add the following line after the reduction which will set the time property and reflect the proper time in the exported image:
`water_img = water_img.set("system:time_start", ee.Date(start_time).millis())`

**Comment by KMarkert** [comment]
Another option to apply the reduction and keep the time information is to use the following code:
`water_map = water_imgs.aggregate_time(reducer=ee.Reducer.mode())`

This method looks at unique dates and applies the specified reducer. Since there is only one date, it produces the one image and keeps the time info. This method is less efficient though as it does a couple operations to check and aggregate time, so use `.aggregate_time()` with that in mind.

Please let me know if I can help with anything else or if you have other suggestions to the docs and package!

**Comment by RussellGrew** [comment]
Hi @KMarkert,

Thanks for your help. Apologies for my delay in trying this out.

I am still unable to get an output image. I feel like my blue box in the screenshot earlier in this ticket should look more like one of the images on your main page?

I tried the below. Code is reproduced here as there was maybe a typo (`img`, `imgs`?) in your example extending the readme.

```
water_map = ee.Image(water_imgs.collection.mode())
water_img = water_map.set("system:time_start", ee.Date(start_time).millis())

# export the water map
hf.geeutils.export_image(
    water_img,
    region,
    "users/russellgrew/github_example2",
    scale=30,
)
```
And your second example
```
water_map = water_imgs.aggregate_time(reducer=ee.Reducer.mode())
# export the water map
hf.geeutils.export_image(
    water_map,
    region,
    "users/russellgrew/github_example3",
    scale=30,
)
```
Yields `'Sentinel1' object has no attribute 'prepare_for_export'`. 

I suppose I was looking for a quick way of preparing an insightful image without needing a deep understanding of the process. 

Maybe this isn't possible?

Cheers.

**Comment by ArjenHaag** [comment]
Hi @RussellGrew,

Sorry I missed this one and thanks for reporting this. What exactly isn't working for you? I think your original output image should work (aside from the fact it had no date). The first option Kel provided to add a date should also work. The fact that you see a 'blue box' in your assets folder doesn't say much, that's just GEE quickly rendering it (and it doesn't know how you'd like to visualize it). You should visualize it yourself to get a true feel of how it looks.

I quickly exported using both the default code from the ReadMe, as well as using Kel's first suggestion here. Here's a link to those images: https://code.earthengine.google.com/01c46979354f4cfd338f970abb080cea. You'll notice both can be displayed on the map (showing the same data), but only the second has a date property.

Cheers.

**Comment by RussellGrew** [comment]
Hi @ArjenHaag thanks for your response.

My Google Cloud trial has expired and I am putting this to the side for now.

It may be that it was working and just needed visualisation as you have shown.
