### ISSUE TITLE
Small Typo in Getting Started Section

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#32]
FYI, I am running this in Google Colaboratory  on Python 3.7.12. 

In the 9th code block on the "Getting Started" Chapter of the HF Documentation, I believe there is a small typo. 

the first line of this code block is as follows

"  #extract bands needed for prediction 
  harmonic_weights = harmonics.select("^c|t|s).*") "

Executing this code block as written produces the following error: 

" NameError: name 'harmonics' is not defined "

In the preceding  code block we define the variable, "harmonics_weights" as follows

" harmonics_weights = timeseries.fit_harmonic_trend(s1, dependent = 'VV', n_cycles = 2) "

Thus, I believe the code block should read as shown:

"  #extract bands needed for prediction 
  harmonic_weights = harmonics_weights.select("^c|t|s).*") "

When I run the code block this way, I get no error and it seems to function as intended. 

Let me know, thanks.

**Comment by KMarkert** [comment]
Thanks for reporting this syntax error and suggesting the change. I will work on fixing the docs with the changes you provided.

**Comment by KMarkert** [comment]
Fixed with 957183f947df6c5e1ff1be188f7a3bbb0bd61c77
