### ISSUE TITLE
Merging Datasets Issue.

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#35]
Hello, 

This error occurs in the "Merging Datasets" section of the "Using the Dataset Class" Chapter of the HF Documentation. (Specifically, the 7th code block in this Chapter)

While there is no error in the code, and everything runs fine, I thought I should mention something interesting I found here, as it may impact a separate issue in this chapter (See Issue #36)

I ran this code in Google Colaboratory on Python 3.7.12. 

The code bock in question reads as follows
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
lc8 = hf.Landsat8(region, start_time,end_time)
#has 197 images

s2 = hf.Sentinel2(region, start_time, end_time)
#has2400 images

merged = lc8.merge(s2)
print(merged.n_images)
#now has 2597 images!
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
While this code predicts 197, 2400, and 2597 images for the variables named lc8, s2, and merged, respectively, I get 71 images for lc8, 798 images for s2, and 869 images for merged.

I get a different number of images than predicted in the following code block as well (located in the "joining datasets" section. 

Thanks in advance!

**Comment by KMarkert** [comment]
Looks like this issue was due to me using different date range than what is in the document when writing. I have updated the expected results in the docs based on what a user will walk through with 4c659dbef8243a28fb603eb06c92f27c4cd7b18e
