### ISSUE TITLE
Potential Missing Code in Documentation

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#36]
Hello, 

This could totally be user error, but there appears to be some missing code in the "Temporal Aggregation" Section of the "Using the Dataset Class" Chapter of the HF documentation.  Specifically it is in the 9th code block of the "Using the Dataset Class" Chapter

This is running in Google Colab on Python 3.7.12. 

Again, the code is perfectly fine, and runs without error. 

The code block is as follows: 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#define new time range
start_time = "2018-11-03"
end_time = "2018-11-15"

#get the terra MODIS dataset
terra = hf.Modis(region, start_time, end_time)
#get the aqua MODIS dataset
#note calling the asset_id explicitly
aqua = hf.Modis(region, start_time, end_time, asset_id="MODIS/006/MYD09GA")

#merge the collections into one
merged = terra.merga(aqua)
#aggregate in time 
agg = merged.aggregate_time(reducer="median")
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
However, in the documentation below this code block, you show three images, one for the terra sensor, one for the agua sensor, and an aggregated image. 

But the above code block does not provide the code to retrieve the URLs to view the image within our own code like it did in the preceding code block (in the "joining dataset" section). 

Thanks in advance!

**Comment by KMarkert** [comment]
Fixed with d4ffadb537d97499a77158e00daa02d07bbc7803
