### ISSUE TITLE
Attribute Error in "Writing your own dataset class" Section.

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#37]
I am running this in Google Colaboratory on Python 3.7.12

This error occurs in the "Using the Dataset Class" Chapter, in the "Writing your own dataset class" section. It is the last code block of the chapter.

When I run the code block as is, Colab throws the following Attribute Error on line 20 of the cell: 

"module: 'hydrafloods.decorators' has no attribute 'carry_metadata' "

When I comment this line out, the cell executes and I am able to view the image seen in the documentation.

**Comment by KMarkert** [comment]
Thanks for the report. This error is occuring because the decorator `carry_metadata` was changes to [`keep_attrs`](https://github.com/Servir-Mekong/hydra-floods/blob/master/hydrafloods/decorators.py#L5).

I will update the docs to reflect the API change.

**Comment by KMarkert** [comment]
Fixed with d583500df92dc7df0ba945752dba7cff85e17994
