### ISSUE TITLE
The Landsat 8 image is deprecated

### ISSUE THREAD

**Issue by JustinWenzhaoLi** [Servir-Mekong/hydra-floods#39]
Hi, 
I find in the GEE that the data used in Landsat8 is deprecated, and This dataset has been superseded by "LANDSAT/LC08/C02/T1_L2"
Does it plan to be updated?

Justin

**Comment by KMarkert** [comment]
Yes, it is planned to update the deprecated collections to collection 2. While at it, I will include Landsat 9 collection 2 data too.

**Comment by 454577snap** [comment]
Through the **Algorithms** workflow you have shared an example of extracting surface water or flooded area, you have used Landsat 8 data, can we use Sentinel 2  too?
